openapi: 3.0.0
info:
  title: Movable Whiteboard
  description: Copy Movable Whiteboard
  version: 1.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /boards:
    get:
      $ref: "./endpoints/boards.yml#/getAllBoards"

    post:
      $ref: "./endpoints/boards.yml#/createBoard"

  /boards/{boardId}:
    delete:
      $ref: "./endpoints/boards.yml#/deleteBoard"

  /auth/login:
    post:
      $ref: "./endpoints/auth.yml#/login"

  /auth/register:
    post:
      $ref: "./endpoints/auth.yml#/register"
  
  /auth/refresh:
    post:
      $ref: "./endpoints/auth.yml#/refresh"
